- include_vars: vars.yml
  tags: always

- block:
  ## User configs
  - import_tasks: users/jvansan.yml
  - import_tasks: setup_packages.yml
    # external software
  - import_tasks: software/terraform.yml
  - import_tasks: software/docker.yml

- block:
  - import_tasks: software/aws_cli.yml
    when: aws_cli is defined and aws_cli == true
